import { GoogleGenAI } from "@google/genai";
import { NextRequest, NextResponse } from "next/server";

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    },
  },
});

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { prompt, type, age, weight, bloodPressure, sugarLevel, symptoms } = body;

    let systemInstruction = "";
    let contents = "";

    if (type === "prediction") {
      systemInstruction = `You are an AI Clinical Risk Assessment Companion.
Analyze the patient's health parameters and symptoms. Provide a structured risk assessment report.
Structure your response output in clean Markdown with the following clearly labeled sections:
1. **Primary Vitals Analysis**: Briefly analyze the stats provided (Weight, Blood Pressure, Sugar Level, Age).
2. **Potential Clinical Risks**: List any potential health risks or correlations based strictly on stats and symptoms.
3. **Recommended Actions**: Outline non-prescriptive, supportive wellness advice.
4. **Urgency Classification**: Select one of: LOW, MEDIUM, or HIGH/URGENT, and justify.
5. **Medical Disclaimer**: Highly prominent explanation that AI does not replace a doctor.

CRITICAL DISCLAIMER REQUIRED: You must explicitly state that 'This assessment is generated by an AI assistant for informational purposes only. It is not a clinical diagnosis and absolutely does not replace a professional evaluation, checkup, or diagnosis by a registered medical practitioner.'`;

      contents = `Patient Details:
- Age: ${age || "N/A"} years old
- Weight: ${weight || "N/A"} kg
- Blood Pressure: ${bloodPressure || "N/A"}
- Sugar Level: ${sugarLevel || "N/A"} mg/dL
- Main Symptoms: ${symptoms || "None specified"}`;
    } else if (type === "symptom") {
      systemInstruction = `You are a helpful AI Symptom Assessment assistant.
Analyze the reported symptoms, mood, and parameters. Suggest basic remedies, possible non-severe diagnoses (with strong caveats), and clarify when they should see a doctor.
CRITICAL: Include the mandatory disclaimer that AI does not replace formal medical consultations.`;

      contents = `Patient Symptom Log:
${prompt}`;
    } else {
      // General conversation / chat
      systemInstruction = `You are a warm, helpful virtual medical coordinator and health coach.
Your task is to answer basic health inquiries, describe what medications are generally used for, give general wellness advice, and support daily health tracking.
CRITICAL: Always append a disclaimer: 'This is AI guidance. Do not change medication schedules or ignore clinical instructions without talking to your doctor.'`;

      contents = prompt;
    }

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents,
      config: {
        systemInstruction,
        temperature: 0.2, // low temperature for logical consistency
      },
    });

    return NextResponse.json({ text: response.text });
  } catch (error: any) {
    console.error("Gemini API Error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Failed to generate health advice from Gemini" },
      { status: 500 }
    );
  }
}
